DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "testing new name",
    "number": "91827364598"
}

###
GET http://localhost:3001/api/persons