DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "testperson",
    "number": "123456789"
}

###
GET http://localhost:3001/api/persons