DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "newname",
    "number": "1029384756"
}

###
GET http://localhost:3001/api/persons